name       : python-pysrt
version    : 1.1.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pysrt/pysrt-1.1.1.tar.gz : fb4c10424549fc5a32d19cd5091f00316b875461fcd79a7809bb55056974d0aa
license    : GPL-3.0-or-later
component  : programming.python
summary    : SubRip (.srt) subtitle parser and writer
description: |
    pysrt is a Python library used to edit or create SubRip files.
builddeps  :
    - python-chardet
rundeps    :
    - python-chardet
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
