name       : python-pysrt
version    : 1.1.1
release    : 1
source     :
    - https://pypi.python.org/packages/f6/33/16ad65a8973cb8bcb494af09ee1b9ab5ffdd6ff300bce5d3ac7d3cb1f2cc/pysrt-1.1.1.tar.gz : fb4c10424549fc5a32d19cd5091f00316b875461fcd79a7809bb55056974d0aa
license    : GPL-3.0
component  : programming.python
summary    : SubRip (.srt) subtitle parser and writer
description: |
    SubRip (.srt) subtitle parser and writer
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
